# Site settings
title: Juan Pablo Prado - A blog about web conferences
email: juan@juanpabloprado.com
#description: A blog about my favorite web conferences.
url: "http://juanpabloprado.github.io" # the base hostname & protocol for your site
twitter_username: juanpablosprado
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title
gems:
  - jekyll-redirect-from

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Juan Prado
      layout: "post"
      category: development
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"





